// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe-hI_JouxbjEUIiP9GUbNYs93dn5yMeA',
    appId: '1:146428320343:web:ccdd55022e4a2e2ca72112',
    messagingSenderId: '146428320343',
    projectId: 'theatre-production-manager',
    authDomain: 'theatre-production-manager.firebaseapp.com',
    storageBucket: 'theatre-production-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCiTB61OgKxpbTxTsBLo774rWcZlH77Ho',
    appId: '1:146428320343:android:118fb475fa96ca4fa72112',
    messagingSenderId: '146428320343',
    projectId: 'theatre-production-manager',
    storageBucket: 'theatre-production-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUznGcJTxTIUtNrFqBktACKlCftMMNick',
    appId: '1:146428320343:ios:1184588a0c513810a72112',
    messagingSenderId: '146428320343',
    projectId: 'theatre-production-manager',
    storageBucket: 'theatre-production-manager.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUznGcJTxTIUtNrFqBktACKlCftMMNick',
    appId: '1:146428320343:ios:1184588a0c513810a72112',
    messagingSenderId: '146428320343',
    projectId: 'theatre-production-manager',
    storageBucket: 'theatre-production-manager.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAe-hI_JouxbjEUIiP9GUbNYs93dn5yMeA',
    appId: '1:146428320343:web:ced3221c8181ce8fa72112',
    messagingSenderId: '146428320343',
    projectId: 'theatre-production-manager',
    authDomain: 'theatre-production-manager.firebaseapp.com',
    storageBucket: 'theatre-production-manager.firebasestorage.app',
  );
}
